server: 
  port: 14801

database: 
  master: "mysql"
  slaves: []
  port: 3306
  username: "gomall"
  password: "gomallpwd"
  name: "order"

redis: 
  host: ["redis:6379"]

kafka_writer: 
  host: ["kafka:9092"]
  username: ""
  password: ""
  topic: [
    "gomall-order-status",
    "gomall-order-status-dmq"
  ]
  group_id: "1"

kafka_reader: 
    host: ["order-kafka:9092"]
    username: "root"
    password: "root"
    topic: 
        - "gomall-order-status"
        - "gomall-order-status-dmq"
    group_id: "1"

