server:
  host: localhost
  port: 14801
  max_http_conns: 100

etcd:
  host:
    - etcd
  tls: false

payment:
  wechat:
    mchID: "114514"
    mchCertificateSerialNumber: "114514"
    mchAPIv3Key: "114514"
    primaryKeyPath: "path/to/your/private_key.pem"
    notifyURL: "http://localhost:14801/v1/payment/notify/wechat"

database:
  master: mysql
  slaves: []
  port: 3306
  username: gomall
  password: gomallpwd
  name: payment

redis:
  host:
    - redis
  port: 6379

kafka_writer:
  host:
    - kafka
  port: "9092"
  username: ""
  password: ""
  topic:
    - gomall-payment-status
    - gomall-payment-status-dmq
  group_id: "1"

kafka_reader:
  host:
    - kafka
  port: "9092"
  username: root
  password: root
  group_id: "1"
  topic:
    - gomall-payment-status
    - gomall-payment-status-dmq