server:
  host: localhost
  port: 14804
  max_http_conns: 100

database:
  master: localhost
  slaves: []
  port: 3306
  username: user
  password: password
  name: payment

redis:
  host:
    - localhost
  port: 6379

kafka_writer:
  host:
    - localhost
  port: "9092"
  username: ""
  password: ""
  topic:
    - gomall-payment-status
    - gomall-payment-status-dmq
  group_id: "1"

kafka_reader:
  host:
    - localhost
  port: "9092"
  username: root
  password: root
  group_id: "1"
  topic:
    - gomall-payment-status
    - gomall-payment-status-dmq