server: 
  port: 14803

database: 
  master: "order-mysql"
  slaves: []
  port: 3306
  username: "test"
  password: "test"
  name: "order"

redis: 
  host: ["order-redis"]
  port: 6379

kafka_writer: 
  host: ["order-kafka:9092"]
  username: ""
  password: ""
  topic: [
    "gomall-order-status",
    "gomall-order-status-dmq"
  ]
  group_id: "1"

kafka_reader: 
    host: ["order-kafka:9092"]
    username: "root"
    password: "root"
    topic: 
        - "gomall-order-status"
        - "gomall-order-status-dmq"
    group_id: "1"

