apiVersion: v1
kind: ConfigMap
metadata:
  name: gomall-config
  namespace: gomall
data:
  config.yaml: |
    # 这里是服务的配置
    server:
      port: 8080
    database:
      host: postgres
      port: 5432
      user: your_db_user
      password: your_db_password
      name: your_db_name
    redis:
      host: redis
      port: 6379
    jwt:
      secret: your_jwt_secret
      expiration: 3600
    logging:
      level: info
      format: json