database:
    host: "mysql"
    port: "3306"
    user: "gomall"
    password: "gomallpwd"
    database: "cart"

redis:
    address: ["redis:6379"]

server:
    port: 14801

kafka:
    brokers: ["kafka:9092"]
    topic: "cart"
