redis:
  host: 
    - localhost
  port: 6379
  password: ""


llm:
  enable: true
  name: deepseek-r1-distill-qwen-7b
  host: http://127.0.0.1:1234/v1/chat/completions
  key: 

embed:
  enable: true
  name: text-embedding-mxbai-embed-large-v1
  host: http://127.0.0.1:1234/v1/embeddings
  key: 