// 订单模块的定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: order.proto

package order

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrderStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusReq) Reset() {
	*x = GetOrderStatusReq{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusReq) ProtoMessage() {}

func (x *GetOrderStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusReq.ProtoReflect.Descriptor instead.
func (*GetOrderStatusReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderStatusReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type GetOrderStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderStatus   int32                  `protobuf:"varint,1,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"` // 产品对应的订单状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderStatusResp) Reset() {
	*x = GetOrderStatusResp{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderStatusResp) ProtoMessage() {}

func (x *GetOrderStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderStatusResp.ProtoReflect.Descriptor instead.
func (*GetOrderStatusResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderStatusResp) GetOrderStatus() int32 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

type ListOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderReq) Reset() {
	*x = ListOrderReq{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderReq) ProtoMessage() {}

func (x *ListOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderReq.ProtoReflect.Descriptor instead.
func (*ListOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *ListOrderReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreetAddress string                 `protobuf:"bytes,1,opt,name=street_address,json=streetAddress,proto3" json:"street_address,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *Address) GetStreetAddress() string {
	if x != nil {
		return x.StreetAddress
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Address       *Address               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Cost          float32                `protobuf:"fixed32,7,opt,name=cost,proto3" json:"cost,omitempty"`
	OrderId       uint64                 `protobuf:"varint,8,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Order) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Order) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Order) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Order) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Order) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Order) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type ListOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderResp) Reset() {
	*x = ListOrderResp{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderResp) ProtoMessage() {}

func (x *ListOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderResp.ProtoReflect.Descriptor instead.
func (*ListOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrderResp) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type ApplyOrderIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"` // 幂等性token
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyOrderIDReq) Reset() {
	*x = ApplyOrderIDReq{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOrderIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOrderIDReq) ProtoMessage() {}

func (x *ApplyOrderIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOrderIDReq.ProtoReflect.Descriptor instead.
func (*ApplyOrderIDReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyOrderIDReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApplyOrderIDReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ApplyOrderIDResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Result        bool                   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyOrderIDResp) Reset() {
	*x = ApplyOrderIDResp{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOrderIDResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOrderIDResp) ProtoMessage() {}

func (x *ApplyOrderIDResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOrderIDResp.ProtoReflect.Descriptor instead.
func (*ApplyOrderIDResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyOrderIDResp) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ApplyOrderIDResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type CreateOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint64                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Address       *Address               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	OrderId       uint64                 `protobuf:"varint,5,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Cost          float32                `protobuf:"fixed32,6,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *CreateOrderReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateOrderReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateOrderReq) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CreateOrderReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CreateOrderReq) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *CreateOrderResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *CancelOrderReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CancelOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResp) Reset() {
	*x = CancelOrderResp{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResp) ProtoMessage() {}

func (x *CancelOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResp.ProtoReflect.Descriptor instead.
func (*CancelOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *CancelOrderResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\".\n" +
	"\x11GetOrderStatusReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"7\n" +
	"\x12GetOrderStatusResp\x12!\n" +
	"\forder_status\x18\x01 \x01(\x05R\vorderStatus\"'\n" +
	"\fListOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"Z\n" +
	"\aAddress\x12%\n" +
	"\x0estreet_address\x18\x01 \x01(\tR\rstreetAddress\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\"\xe7\x01\n" +
	"\x05Order\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04R\tproductId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12(\n" +
	"\aaddress\x18\x04 \x01(\v2\x0e.order.AddressR\aaddress\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x12\n" +
	"\x04cost\x18\a \x01(\x02R\x04cost\x12\x19\n" +
	"\border_id\x18\b \x01(\x04R\aorderId\"5\n" +
	"\rListOrderResp\x12$\n" +
	"\x06orders\x18\x01 \x03(\v2\f.order.OrderR\x06orders\"@\n" +
	"\x0fApplyOrderIDReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"E\n" +
	"\x10ApplyOrderIDResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\bR\x06result\"\xb9\x01\n" +
	"\x0eCreateOrderReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\x04R\tproductId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\x12(\n" +
	"\aaddress\x18\x04 \x01(\v2\x0e.order.AddressR\aaddress\x12\x19\n" +
	"\border_id\x18\x05 \x01(\x04R\aorderId\x12\x12\n" +
	"\x04cost\x18\x06 \x01(\x02R\x04cost\")\n" +
	"\x0fCreateOrderResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"+\n" +
	"\x0eCancelOrderReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\")\n" +
	"\x0fCancelOrderResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result2\xd4\x02\n" +
	"\fOrderService\x128\n" +
	"\tListOrder\x12\x13.order.ListOrderReq\x1a\x14.order.ListOrderResp\"\x00\x12G\n" +
	"\x0eGetOrderStatus\x12\x18.order.GetOrderStatusReq\x1a\x19.order.GetOrderStatusResp\"\x00\x12A\n" +
	"\fApplyOrderID\x12\x16.order.ApplyOrderIDReq\x1a\x17.order.ApplyOrderIDResp\"\x00\x12>\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\"\x00\x12>\n" +
	"\vCancelOrder\x12\x15.order.CancelOrderReq\x1a\x16.order.CancelOrderResp\"\x00B!Z\x1fbytedancemall/order/proto;orderb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_order_proto_goTypes = []any{
	(*GetOrderStatusReq)(nil),  // 0: order.GetOrderStatusReq
	(*GetOrderStatusResp)(nil), // 1: order.GetOrderStatusResp
	(*ListOrderReq)(nil),       // 2: order.ListOrderReq
	(*Address)(nil),            // 3: order.Address
	(*Order)(nil),              // 4: order.Order
	(*ListOrderResp)(nil),      // 5: order.ListOrderResp
	(*ApplyOrderIDReq)(nil),    // 6: order.ApplyOrderIDReq
	(*ApplyOrderIDResp)(nil),   // 7: order.ApplyOrderIDResp
	(*CreateOrderReq)(nil),     // 8: order.CreateOrderReq
	(*CreateOrderResp)(nil),    // 9: order.CreateOrderResp
	(*CancelOrderReq)(nil),     // 10: order.CancelOrderReq
	(*CancelOrderResp)(nil),    // 11: order.CancelOrderResp
}
var file_order_proto_depIdxs = []int32{
	3,  // 0: order.Order.address:type_name -> order.Address
	4,  // 1: order.ListOrderResp.orders:type_name -> order.Order
	3,  // 2: order.CreateOrderReq.address:type_name -> order.Address
	2,  // 3: order.OrderService.ListOrder:input_type -> order.ListOrderReq
	0,  // 4: order.OrderService.GetOrderStatus:input_type -> order.GetOrderStatusReq
	6,  // 5: order.OrderService.ApplyOrderID:input_type -> order.ApplyOrderIDReq
	8,  // 6: order.OrderService.CreateOrder:input_type -> order.CreateOrderReq
	10, // 7: order.OrderService.CancelOrder:input_type -> order.CancelOrderReq
	5,  // 8: order.OrderService.ListOrder:output_type -> order.ListOrderResp
	1,  // 9: order.OrderService.GetOrderStatus:output_type -> order.GetOrderStatusResp
	7,  // 10: order.OrderService.ApplyOrderID:output_type -> order.ApplyOrderIDResp
	9,  // 11: order.OrderService.CreateOrder:output_type -> order.CreateOrderResp
	11, // 12: order.OrderService.CancelOrder:output_type -> order.CancelOrderResp
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
