FROM golang:1.25.1 AS builder

WORKDIR /app

COPY . .

RUN go env -w  GOPROXY=https://goproxy.io,direct
RUN go mod tidy
RUN go build -o payment-service ./cmd

RUN ls -l /app

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/payment-service .
# 如果有配置文件，记得也复制它
COPY --from=builder /app/config.yaml .

EXPOSE 14804
CMD ["./payment-service"]