version: '3.8'

services:
  redis:
    image: redis:8
    container_name: auth_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  redis_data: