FROM golang:1.25.1 AS builder

WORKDIR /app

COPY . .

RUN go env -w  GOPROXY=https://goproxy.io,direct
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o order-service ./cmd/main.go
RUN ls -l /app

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/order-service .
COPY config.yaml /app/config.yaml

ENV CONFIG_PATH=config.yaml

EXPOSE 14803
CMD ["./order-service"]