FROM golang:1.25.1 AS builder

WORKDIR /app
COPY . .
RUN go env -w  GOPROXY=https://goproxy.io,direct
RUN go mod tidy
RUN CGO_ENABLED=0 go build -o product-service .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/product-service .
COPY --from=builder /app/config.yaml .

EXPOSE 8080
CMD ["./product-service"]