// 库存模块的定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeduatInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InventoryId   uint64                 `protobuf:"varint,1,opt,name=inventory_id,json=inventoryId,proto3" json:"inventory_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeduatInventoryReq) Reset() {
	*x = DeduatInventoryReq{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeduatInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeduatInventoryReq) ProtoMessage() {}

func (x *DeduatInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeduatInventoryReq.ProtoReflect.Descriptor instead.
func (*DeduatInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *DeduatInventoryReq) GetInventoryId() uint64 {
	if x != nil {
		return x.InventoryId
	}
	return 0
}

func (x *DeduatInventoryReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DeduatInventoryReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type DeduatInventoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeduatInventoryResp) Reset() {
	*x = DeduatInventoryResp{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeduatInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeduatInventoryResp) ProtoMessage() {}

func (x *DeduatInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeduatInventoryResp.ProtoReflect.Descriptor instead.
func (*DeduatInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *DeduatInventoryResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type RecoverInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverInventoryReq) Reset() {
	*x = RecoverInventoryReq{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverInventoryReq) ProtoMessage() {}

func (x *RecoverInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverInventoryReq.ProtoReflect.Descriptor instead.
func (*RecoverInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *RecoverInventoryReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RecoverInventoryReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RecoverInventoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecoverInventoryResp) Reset() {
	*x = RecoverInventoryResp{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecoverInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecoverInventoryResp) ProtoMessage() {}

func (x *RecoverInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecoverInventoryResp.ProtoReflect.Descriptor instead.
func (*RecoverInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *RecoverInventoryResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n" +
	"\x0finventory.proto\x12\tinventory\"j\n" +
	"\x12DeduatInventoryReq\x12!\n" +
	"\finventory_id\x18\x01 \x01(\x04R\vinventoryId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x04R\x06amount\"-\n" +
	"\x13DeduatInventoryResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"H\n" +
	"\x13RecoverInventoryReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x04R\x06amount\".\n" +
	"\x14RecoverInventoryResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result2\xbd\x01\n" +
	"\x10InventoryService\x12R\n" +
	"\x0fDeduatInventory\x12\x1d.inventory.DeduatInventoryReq\x1a\x1e.inventory.DeduatInventoryResp\"\x00\x12U\n" +
	"\x10RecoverInventory\x12\x1e.inventory.RecoverInventoryReq\x1a\x1f.inventory.RecoverInventoryResp\"\x00B)Z'bytedancemall/inventory/proto;inventoryb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inventory_proto_goTypes = []any{
	(*DeduatInventoryReq)(nil),   // 0: inventory.DeduatInventoryReq
	(*DeduatInventoryResp)(nil),  // 1: inventory.DeduatInventoryResp
	(*RecoverInventoryReq)(nil),  // 2: inventory.RecoverInventoryReq
	(*RecoverInventoryResp)(nil), // 3: inventory.RecoverInventoryResp
}
var file_inventory_proto_depIdxs = []int32{
	0, // 0: inventory.InventoryService.DeduatInventory:input_type -> inventory.DeduatInventoryReq
	2, // 1: inventory.InventoryService.RecoverInventory:input_type -> inventory.RecoverInventoryReq
	1, // 2: inventory.InventoryService.DeduatInventory:output_type -> inventory.DeduatInventoryResp
	3, // 3: inventory.InventoryService.RecoverInventory:output_type -> inventory.RecoverInventoryResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
