// 大模型定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: llm.proto

package llm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FilterKeyWordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterKeyWordReq) Reset() {
	*x = FilterKeyWordReq{}
	mi := &file_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterKeyWordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterKeyWordReq) ProtoMessage() {}

func (x *FilterKeyWordReq) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterKeyWordReq.ProtoReflect.Descriptor instead.
func (*FilterKeyWordReq) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{0}
}

func (x *FilterKeyWordReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

type FilterKeyWordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterKeyWordResp) Reset() {
	*x = FilterKeyWordResp{}
	mi := &file_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterKeyWordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterKeyWordResp) ProtoMessage() {}

func (x *FilterKeyWordResp) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterKeyWordResp.ProtoReflect.Descriptor instead.
func (*FilterKeyWordResp) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{1}
}

func (x *FilterKeyWordResp) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Describe      string                 `protobuf:"bytes,1,opt,name=Describe,proto3" json:"Describe,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Quantity      uint32                 `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Id            uint32                 `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{2}
}

func (x *Product) GetDescribe() string {
	if x != nil {
		return x.Describe
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ChooseProductReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductInfo   []*Product             `protobuf:"bytes,1,rep,name=product_info,json=productInfo,proto3" json:"product_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseProductReq) Reset() {
	*x = ChooseProductReq{}
	mi := &file_llm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseProductReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseProductReq) ProtoMessage() {}

func (x *ChooseProductReq) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseProductReq.ProtoReflect.Descriptor instead.
func (*ChooseProductReq) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{3}
}

func (x *ChooseProductReq) GetProductInfo() []*Product {
	if x != nil {
		return x.ProductInfo
	}
	return nil
}

type ChooseProductResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     []uint32               `protobuf:"varint,1,rep,packed,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseProductResp) Reset() {
	*x = ChooseProductResp{}
	mi := &file_llm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseProductResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseProductResp) ProtoMessage() {}

func (x *ChooseProductResp) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseProductResp.ProtoReflect.Descriptor instead.
func (*ChooseProductResp) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{4}
}

func (x *ChooseProductResp) GetProductId() []uint32 {
	if x != nil {
		return x.ProductId
	}
	return nil
}

var File_llm_proto protoreflect.FileDescriptor

const file_llm_proto_rawDesc = "" +
	"\n" +
	"\tllm.proto\x12\x03llm\",\n" +
	"\x10FilterKeyWordReq\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\"+\n" +
	"\x11FilterKeyWordResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"e\n" +
	"\aProduct\x12\x1a\n" +
	"\bDescribe\x18\x01 \x01(\tR\bDescribe\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\rR\bquantity\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\rR\x02id\"C\n" +
	"\x10ChooseProductReq\x12/\n" +
	"\fproduct_info\x18\x01 \x03(\v2\f.llm.ProductR\vproductInfo\"2\n" +
	"\x11ChooseProductResp\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x03(\rR\tproductId2\x90\x01\n" +
	"\n" +
	"LLMService\x12@\n" +
	"\rFilterKeyWord\x12\x15.llm.FilterKeyWordReq\x1a\x16.llm.FilterKeyWordResp\"\x00\x12@\n" +
	"\rChooseProduct\x12\x15.llm.ChooseProductReq\x1a\x16.llm.ChooseProductResp\"\x00B\x06Z\x04/llmb\x06proto3"

var (
	file_llm_proto_rawDescOnce sync.Once
	file_llm_proto_rawDescData []byte
)

func file_llm_proto_rawDescGZIP() []byte {
	file_llm_proto_rawDescOnce.Do(func() {
		file_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)))
	})
	return file_llm_proto_rawDescData
}

var file_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_llm_proto_goTypes = []any{
	(*FilterKeyWordReq)(nil),  // 0: llm.FilterKeyWordReq
	(*FilterKeyWordResp)(nil), // 1: llm.FilterKeyWordResp
	(*Product)(nil),           // 2: llm.Product
	(*ChooseProductReq)(nil),  // 3: llm.ChooseProductReq
	(*ChooseProductResp)(nil), // 4: llm.ChooseProductResp
}
var file_llm_proto_depIdxs = []int32{
	2, // 0: llm.ChooseProductReq.product_info:type_name -> llm.Product
	0, // 1: llm.LLMService.FilterKeyWord:input_type -> llm.FilterKeyWordReq
	3, // 2: llm.LLMService.ChooseProduct:input_type -> llm.ChooseProductReq
	1, // 3: llm.LLMService.FilterKeyWord:output_type -> llm.FilterKeyWordResp
	4, // 4: llm.LLMService.ChooseProduct:output_type -> llm.ChooseProductResp
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_llm_proto_init() }
func file_llm_proto_init() {
	if File_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_proto_goTypes,
		DependencyIndexes: file_llm_proto_depIdxs,
		MessageInfos:      file_llm_proto_msgTypes,
	}.Build()
	File_llm_proto = out.File
	file_llm_proto_goTypes = nil
	file_llm_proto_depIdxs = nil
}
