// 秒杀模块的定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: seckill.proto

package seckill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 参数定义
type AddItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint32                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      uint32                 `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReleaseTime   string                 `protobuf:"bytes,3,opt,name=release_time,json=releaseTime,proto3" json:"release_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemReq) Reset() {
	*x = AddItemReq{}
	mi := &file_seckill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemReq) ProtoMessage() {}

func (x *AddItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemReq.ProtoReflect.Descriptor instead.
func (*AddItemReq) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{0}
}

func (x *AddItemReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *AddItemReq) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *AddItemReq) GetReleaseTime() string {
	if x != nil {
		return x.ReleaseTime
	}
	return ""
}

type AddItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResp) Reset() {
	*x = AddItemResp{}
	mi := &file_seckill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResp) ProtoMessage() {}

func (x *AddItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResp.ProtoReflect.Descriptor instead.
func (*AddItemResp) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type TrySecKillItemReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrySecKillItemReq) Reset() {
	*x = TrySecKillItemReq{}
	mi := &file_seckill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrySecKillItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrySecKillItemReq) ProtoMessage() {}

func (x *TrySecKillItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrySecKillItemReq.ProtoReflect.Descriptor instead.
func (*TrySecKillItemReq) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{2}
}

func (x *TrySecKillItemReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TrySecKillItemReq) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type TrySecKillItemResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        int32                  `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrySecKillItemResp) Reset() {
	*x = TrySecKillItemResp{}
	mi := &file_seckill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrySecKillItemResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrySecKillItemResp) ProtoMessage() {}

func (x *TrySecKillItemResp) ProtoReflect() protoreflect.Message {
	mi := &file_seckill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrySecKillItemResp.ProtoReflect.Descriptor instead.
func (*TrySecKillItemResp) Descriptor() ([]byte, []int) {
	return file_seckill_proto_rawDescGZIP(), []int{3}
}

func (x *TrySecKillItemResp) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_seckill_proto protoreflect.FileDescriptor

const file_seckill_proto_rawDesc = "" +
	"\n" +
	"\rseckill.proto\x12\aseckill\"j\n" +
	"\n" +
	"AddItemReq\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\rR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\rR\bquantity\x12!\n" +
	"\frelease_time\x18\x03 \x01(\tR\vreleaseTime\"%\n" +
	"\vAddItemResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"K\n" +
	"\x11TrySecKillItemReq\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\rR\tproductId\",\n" +
	"\x12TrySecKillItemResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\x05R\x06result2\x95\x01\n" +
	"\x0eSeckillService\x126\n" +
	"\aAddItem\x12\x13.seckill.AddItemReq\x1a\x14.seckill.AddItemResp\"\x00\x12K\n" +
	"\x0eTrySecKillItem\x12\x1a.seckill.TrySecKillItemReq\x1a\x1b.seckill.TrySecKillItemResp\"\x00B\n" +
	"Z\b/seckillb\x06proto3"

var (
	file_seckill_proto_rawDescOnce sync.Once
	file_seckill_proto_rawDescData []byte
)

func file_seckill_proto_rawDescGZIP() []byte {
	file_seckill_proto_rawDescOnce.Do(func() {
		file_seckill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)))
	})
	return file_seckill_proto_rawDescData
}

var file_seckill_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_seckill_proto_goTypes = []any{
	(*AddItemReq)(nil),         // 0: seckill.AddItemReq
	(*AddItemResp)(nil),        // 1: seckill.AddItemResp
	(*TrySecKillItemReq)(nil),  // 2: seckill.TrySecKillItemReq
	(*TrySecKillItemResp)(nil), // 3: seckill.TrySecKillItemResp
}
var file_seckill_proto_depIdxs = []int32{
	0, // 0: seckill.SeckillService.AddItem:input_type -> seckill.AddItemReq
	2, // 1: seckill.SeckillService.TrySecKillItem:input_type -> seckill.TrySecKillItemReq
	1, // 2: seckill.SeckillService.AddItem:output_type -> seckill.AddItemResp
	3, // 3: seckill.SeckillService.TrySecKillItem:output_type -> seckill.TrySecKillItemResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_seckill_proto_init() }
func file_seckill_proto_init() {
	if File_seckill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_seckill_proto_rawDesc), len(file_seckill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_seckill_proto_goTypes,
		DependencyIndexes: file_seckill_proto_depIdxs,
		MessageInfos:      file_seckill_proto_msgTypes,
	}.Build()
	File_seckill_proto = out.File
	file_seckill_proto_goTypes = nil
	file_seckill_proto_depIdxs = nil
}
