// 库存模块的定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *Product) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PreheatInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreheatInventoryReq) Reset() {
	*x = PreheatInventoryReq{}
	mi := &file_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreheatInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreheatInventoryReq) ProtoMessage() {}

func (x *PreheatInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreheatInventoryReq.ProtoReflect.Descriptor instead.
func (*PreheatInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *PreheatInventoryReq) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

type PreheatInventoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreheatInventoryResp) Reset() {
	*x = PreheatInventoryResp{}
	mi := &file_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreheatInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreheatInventoryResp) ProtoMessage() {}

func (x *PreheatInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreheatInventoryResp.ProtoReflect.Descriptor instead.
func (*PreheatInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *PreheatInventoryResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type DeductInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductInventoryReq) Reset() {
	*x = DeductInventoryReq{}
	mi := &file_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductInventoryReq) ProtoMessage() {}

func (x *DeductInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductInventoryReq.ProtoReflect.Descriptor instead.
func (*DeductInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *DeductInventoryReq) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

func (x *DeductInventoryReq) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type DeductInventoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	RecordId      string                 `protobuf:"bytes,2,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductInventoryResp) Reset() {
	*x = DeductInventoryResp{}
	mi := &file_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductInventoryResp) ProtoMessage() {}

func (x *DeductInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductInventoryResp.ProtoReflect.Descriptor instead.
func (*DeductInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *DeductInventoryResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *DeductInventoryResp) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

type CreateInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        uint64                 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryReq) Reset() {
	*x = CreateInventoryReq{}
	mi := &file_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryReq) ProtoMessage() {}

func (x *CreateInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryReq.ProtoReflect.Descriptor instead.
func (*CreateInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *CreateInventoryReq) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *CreateInventoryReq) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateInventoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInventoryResp) Reset() {
	*x = CreateInventoryResp{}
	mi := &file_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInventoryResp) ProtoMessage() {}

func (x *CreateInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInventoryResp.ProtoReflect.Descriptor instead.
func (*CreateInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *CreateInventoryResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type DeleteInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryReq) Reset() {
	*x = DeleteInventoryReq{}
	mi := &file_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryReq) ProtoMessage() {}

func (x *DeleteInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryReq.ProtoReflect.Descriptor instead.
func (*DeleteInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteInventoryReq) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type DeleteInventoryResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInventoryResp) Reset() {
	*x = DeleteInventoryResp{}
	mi := &file_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInventoryResp) ProtoMessage() {}

func (x *DeleteInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInventoryResp.ProtoReflect.Descriptor instead.
func (*DeleteInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteInventoryResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type QueryInventoryReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryInventoryReq) Reset() {
	*x = QueryInventoryReq{}
	mi := &file_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInventoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInventoryReq) ProtoMessage() {}

func (x *QueryInventoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInventoryReq.ProtoReflect.Descriptor instead.
func (*QueryInventoryReq) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *QueryInventoryReq) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

type QueryInventoryResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProductId      uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	AvailableStock uint64                 `protobuf:"varint,2,opt,name=available_stock,json=availableStock,proto3" json:"available_stock,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryInventoryResp) Reset() {
	*x = QueryInventoryResp{}
	mi := &file_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryInventoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryInventoryResp) ProtoMessage() {}

func (x *QueryInventoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryInventoryResp.ProtoReflect.Descriptor instead.
func (*QueryInventoryResp) Descriptor() ([]byte, []int) {
	return file_inventory_proto_rawDescGZIP(), []int{10}
}

func (x *QueryInventoryResp) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *QueryInventoryResp) GetAvailableStock() uint64 {
	if x != nil {
		return x.AvailableStock
	}
	return 0
}

var File_inventory_proto protoreflect.FileDescriptor

const file_inventory_proto_rawDesc = "" +
	"\n\x0finventory.proto\x12\tinventory\"@\n\a" +
	"Product\x12\x1d\n\nproduct_id\x18\x01 \x01(\x04R\tpro" +
	"ductId\x12\x16\n\x06amount\x18\x02 \x01(\x04R\x06amount\"E" +
	"\n\x13PreheatInventoryReq\x12.\n\bproduct" +
	"s\x18\x01 \x03(\v2\x12.inventory.ProductR\bpro" +
	"ducts\".\n\x14PreheatInventoryResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"]\n\x12DeductI" +
	"nventoryReq\x12,\n\aproduct\x18\x01 \x01(\v2\x12.i" +
	"nventory.ProductR\aproduct\x12\x1b\n\trec" +
	"ord_id\x18\x02 \x01(\tR\brecordId\"J\n\x13DeductIn" +
	"ventoryResp\x12\x16\n\x06result\x18\x01 \x01(\bR\x06res" +
	"ult\x12\x1b\n\trecord_id\x18\x02 \x01(\tR\brecordId" +
	"\"K\n\x12CreateInventoryReq\x12\x1d\n\nproduc" +
	"t_id\x18\x01 \x01(\x04R\tproductId\x12\x16\n\x06amount\x18" +
	"\x02 \x01(\x04R\x06amount\"-\n\x13CreateInventory" +
	"Resp\x12\x16\n\x06result\x18\x01 \x01(\bR\x06result\"3\n\x12" +
	"DeleteInventoryReq\x12\x1d\n\nproduct_id" +
	"\x18\x01 \x01(\x04R\tproductId\"-\n\x13DeleteInven" +
	"toryResp\x12\x16\n\x06result\x18\x01 \x01(\bR\x06result" +
	"\"2\n\x11QueryInventoryReq\x12\x1d\n\nproduct" +
	"_id\x18\x01 \x01(\x04R\tproductId\"\\\n\x12QueryInv" +
	"entoryResp\x12\x1d\n\nproduct_id\x18\x01 \x01(\x04R\t" +
	"productId\x12'\n\x0favailable_stock\x18\x02 \x01" +
	"(\x04R\x0eavailableStock2\xb6\x03\n\x10Inventory" +
	"Service\x12U\n\x10PreheatInventory\x12\x1e.in" +
	"ventory.PreheatInventoryReq\x1a\x1f.in" +
	"ventory.PreheatInventoryResp\"\x00\x12R" +
	"\n\x0fDeductInventory\x12\x1d.inventory.De" +
	"ductInventoryReq\x1a\x1e.inventory.Ded" +
	"uctInventoryResp\"\x00\x12R\n\x0fCreateInve" +
	"ntory\x12\x1d.inventory.CreateInventor" +
	"yReq\x1a\x1e.inventory.CreateInventory" +
	"Resp\"\x00\x12R\n\x0fDeleteInventory\x12\x1d.inve" +
	"ntory.DeleteInventoryReq\x1a\x1e.inven" +
	"tory.DeleteInventoryResp\"\x00\x12O\n\x0eQu" +
	"eryInventory\x12\x1c.inventory.QueryIn" +
	"ventoryReq\x1a\x1d.inventory.QueryInve" +
	"ntoryResp\"\x00B)Z'bytedancemall/inv" +
	"entory/proto;inventoryb\x06proto3"

var (
	file_inventory_proto_rawDescOnce sync.Once
	file_inventory_proto_rawDescData []byte
)

func file_inventory_proto_rawDescGZIP() []byte {
	file_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)))
	})
	return file_inventory_proto_rawDescData
}

var file_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_inventory_proto_goTypes = []any{
	(*Product)(nil),              // 0: inventory.Product
	(*PreheatInventoryReq)(nil),  // 1: inventory.PreheatInventoryReq
	(*PreheatInventoryResp)(nil), // 2: inventory.PreheatInventoryResp
	(*DeductInventoryReq)(nil),   // 3: inventory.DeductInventoryReq
	(*DeductInventoryResp)(nil),  // 4: inventory.DeductInventoryResp
	(*CreateInventoryReq)(nil),   // 5: inventory.CreateInventoryReq
	(*CreateInventoryResp)(nil),  // 6: inventory.CreateInventoryResp
	(*DeleteInventoryReq)(nil),   // 7: inventory.DeleteInventoryReq
	(*DeleteInventoryResp)(nil),  // 8: inventory.DeleteInventoryResp
	(*QueryInventoryReq)(nil),    // 9: inventory.QueryInventoryReq
	(*QueryInventoryResp)(nil),   // 10: inventory.QueryInventoryResp
}
var file_inventory_proto_depIdxs = []int32{
	0,  // 0: inventory.PreheatInventoryReq.products:type_name -> inventory.Product
	0,  // 1: inventory.DeductInventoryReq.product:type_name -> inventory.Product
	1,  // 2: inventory.InventoryService.PreheatInventory:input_type -> inventory.PreheatInventoryReq
	3,  // 3: inventory.InventoryService.DeductInventory:input_type -> inventory.DeductInventoryReq
	5,  // 4: inventory.InventoryService.CreateInventory:input_type -> inventory.CreateInventoryReq
	7,  // 5: inventory.InventoryService.DeleteInventory:input_type -> inventory.DeleteInventoryReq
	9,  // 6: inventory.InventoryService.QueryInventory:input_type -> inventory.QueryInventoryReq
	2,  // 7: inventory.InventoryService.PreheatInventory:output_type -> inventory.PreheatInventoryResp
	4,  // 8: inventory.InventoryService.DeductInventory:output_type -> inventory.DeductInventoryResp
	6,  // 9: inventory.InventoryService.CreateInventory:output_type -> inventory.CreateInventoryResp
	8,  // 10: inventory.InventoryService.DeleteInventory:output_type -> inventory.DeleteInventoryResp
	10, // 11: inventory.InventoryService.QueryInventory:output_type -> inventory.QueryInventoryResp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_inventory_proto_init() }
func file_inventory_proto_init() {
	if File_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_proto_rawDesc), len(file_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_proto_depIdxs,
		MessageInfos:      file_inventory_proto_msgTypes,
	}.Build()
	File_inventory_proto = out.File
	file_inventory_proto_goTypes = nil
	file_inventory_proto_depIdxs = nil
}
