version: '3.8'

services:
  redis:
    image: redis:8
    container_name: auth_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mysql:
    image: mysql:8.0
    container_name: auth_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  auth:
    build:
      context: ..
      dockerfile: ./docker/dockerfile
    container_name: gomall_auth
    ports:
      - "14801:14801"
    depends_on:
      - redis
      - mysql
    environment:
      - CONFIG_PATH=/app/config.yaml
    command: ["./gomall-auth", "-config", "/app/config.yaml"]
volumes:
  redis_data:
  mysql_data: