// 大模型定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: llm.proto

package llm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Question      string                 `protobuf:"bytes,1,opt,name=question,proto3" json:"question,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuestionReq) Reset() {
	*x = QuestionReq{}
	mi := &file_llm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuestionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuestionReq) ProtoMessage() {}

func (x *QuestionReq) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuestionReq.ProtoReflect.Descriptor instead.
func (*QuestionReq) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{0}
}

func (x *QuestionReq) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

type CustomerAnswerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	Result        bool                   `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerAnswerResp) Reset() {
	*x = CustomerAnswerResp{}
	mi := &file_llm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerAnswerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerAnswerResp) ProtoMessage() {}

func (x *CustomerAnswerResp) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerAnswerResp.ProtoReflect.Descriptor instead.
func (*CustomerAnswerResp) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{1}
}

func (x *CustomerAnswerResp) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *CustomerAnswerResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type AssistantAnswerResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`
	ProductIds    []uint64               `protobuf:"varint,2,rep,packed,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	Result        bool                   `protobuf:"varint,3,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssistantAnswerResp) Reset() {
	*x = AssistantAnswerResp{}
	mi := &file_llm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssistantAnswerResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssistantAnswerResp) ProtoMessage() {}

func (x *AssistantAnswerResp) ProtoReflect() protoreflect.Message {
	mi := &file_llm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssistantAnswerResp.ProtoReflect.Descriptor instead.
func (*AssistantAnswerResp) Descriptor() ([]byte, []int) {
	return file_llm_proto_rawDescGZIP(), []int{2}
}

func (x *AssistantAnswerResp) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AssistantAnswerResp) GetProductIds() []uint64 {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *AssistantAnswerResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_llm_proto protoreflect.FileDescriptor

const file_llm_proto_rawDesc = "" +
	"\n" +
	"\tllm.proto\x12\x03llm\")\n" +
	"\vQuestionReq\x12\x1a\n" +
	"\bquestion\x18\x01 \x01(\tR\bquestion\"D\n" +
	"\x12CustomerAnswerResp\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x16\n" +
	"\x06result\x18\x02 \x01(\bR\x06result\"f\n" +
	"\x13AssistantAnswerResp\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1f\n" +
	"\vproduct_ids\x18\x02 \x03(\x04R\n" +
	"productIds\x12\x16\n" +
	"\x06result\x18\x03 \x01(\bR\x06result2\x8f\x01\n" +
	"\n" +
	"LLMService\x12B\n" +
	"\x13IntelligentCustomer\x12\x10.llm.QuestionReq\x1a\x17.llm.CustomerAnswerResp\"\x00\x12=\n" +
	"\rShopAssistant\x12\x10.llm.QuestionReq\x1a\x18.llm.AssistantAnswerResp\"\x00B\x06Z\x04/llmb\x06proto3"

var (
	file_llm_proto_rawDescOnce sync.Once
	file_llm_proto_rawDescData []byte
)

func file_llm_proto_rawDescGZIP() []byte {
	file_llm_proto_rawDescOnce.Do(func() {
		file_llm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)))
	})
	return file_llm_proto_rawDescData
}

var file_llm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_llm_proto_goTypes = []any{
	(*QuestionReq)(nil),         // 0: llm.QuestionReq
	(*CustomerAnswerResp)(nil),  // 1: llm.CustomerAnswerResp
	(*AssistantAnswerResp)(nil), // 2: llm.AssistantAnswerResp
}
var file_llm_proto_depIdxs = []int32{
	0, // 0: llm.LLMService.IntelligentCustomer:input_type -> llm.QuestionReq
	0, // 1: llm.LLMService.ShopAssistant:input_type -> llm.QuestionReq
	1, // 2: llm.LLMService.IntelligentCustomer:output_type -> llm.CustomerAnswerResp
	2, // 3: llm.LLMService.ShopAssistant:output_type -> llm.AssistantAnswerResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_llm_proto_init() }
func file_llm_proto_init() {
	if File_llm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_llm_proto_rawDesc), len(file_llm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_llm_proto_goTypes,
		DependencyIndexes: file_llm_proto_depIdxs,
		MessageInfos:      file_llm_proto_msgTypes,
	}.Build()
	File_llm_proto = out.File
	file_llm_proto_goTypes = nil
	file_llm_proto_depIdxs = nil
}
