// 支付模块的定义

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyChargeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          float32                `protobuf:"fixed32,1,opt,name=cost,proto3" json:"cost,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Method        int32                  `protobuf:"varint,4,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyChargeReq) Reset() {
	*x = ApplyChargeReq{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyChargeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyChargeReq) ProtoMessage() {}

func (x *ApplyChargeReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyChargeReq.ProtoReflect.Descriptor instead.
func (*ApplyChargeReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyChargeReq) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ApplyChargeReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ApplyChargeReq) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ApplyChargeReq) GetMethod() int32 {
	if x != nil {
		return x.Method
	}
	return 0
}

type ApplyChargeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderStr      string                 `protobuf:"bytes,1,opt,name=order_str,json=orderStr,proto3" json:"order_str,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyChargeResp) Reset() {
	*x = ApplyChargeResp{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyChargeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyChargeResp) ProtoMessage() {}

func (x *ApplyChargeResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyChargeResp.ProtoReflect.Descriptor instead.
func (*ApplyChargeResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyChargeResp) GetOrderStr() string {
	if x != nil {
		return x.OrderStr
	}
	return ""
}

type CancelChargeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelChargeReq) Reset() {
	*x = CancelChargeReq{}
	mi := &file_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelChargeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelChargeReq) ProtoMessage() {}

func (x *CancelChargeReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelChargeReq.ProtoReflect.Descriptor instead.
func (*CancelChargeReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{2}
}

func (x *CancelChargeReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type CancelChargeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelChargeResp) Reset() {
	*x = CancelChargeResp{}
	mi := &file_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelChargeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelChargeResp) ProtoMessage() {}

func (x *CancelChargeResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelChargeResp.ProtoReflect.Descriptor instead.
func (*CancelChargeResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{3}
}

func (x *CancelChargeResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type QueryStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatusReq) Reset() {
	*x = QueryStatusReq{}
	mi := &file_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatusReq) ProtoMessage() {}

func (x *QueryStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatusReq.ProtoReflect.Descriptor instead.
func (*QueryStatusReq) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{4}
}

func (x *QueryStatusReq) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type QueryStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatusResp) Reset() {
	*x = QueryStatusResp{}
	mi := &file_payment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatusResp) ProtoMessage() {}

func (x *QueryStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatusResp.ProtoReflect.Descriptor instead.
func (*QueryStatusResp) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{5}
}

func (x *QueryStatusResp) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *QueryStatusResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *QueryStatusResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x12\apayment\"p\n" +
	"\x0eApplyChargeReq\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\x02R\x04cost\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06method\x18\x04 \x01(\x05R\x06method\".\n" +
	"\x0fApplyChargeResp\x12\x1b\n" +
	"\torder_str\x18\x01 \x01(\tR\borderStr\",\n" +
	"\x0fCancelChargeReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\",\n" +
	"\x10CancelChargeResp\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"+\n" +
	"\x0eQueryStatusReq\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"^\n" +
	"\x0fQueryStatusResp\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xdf\x01\n" +
	"\x0ePaymentService\x12B\n" +
	"\vApplyCharge\x12\x17.payment.ApplyChargeReq\x1a\x18.payment.ApplyChargeResp\"\x00\x12E\n" +
	"\fCancelCharge\x12\x18.payment.CancelChargeReq\x1a\x19.payment.CancelChargeResp\"\x00\x12B\n" +
	"\vQueryStatus\x12\x17.payment.QueryStatusReq\x1a\x18.payment.QueryStatusResp\"\x00B%Z#bytedancemall/payment/proto;paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_payment_proto_goTypes = []any{
	(*ApplyChargeReq)(nil),   // 0: payment.ApplyChargeReq
	(*ApplyChargeResp)(nil),  // 1: payment.ApplyChargeResp
	(*CancelChargeReq)(nil),  // 2: payment.CancelChargeReq
	(*CancelChargeResp)(nil), // 3: payment.CancelChargeResp
	(*QueryStatusReq)(nil),   // 4: payment.QueryStatusReq
	(*QueryStatusResp)(nil),  // 5: payment.QueryStatusResp
}
var file_payment_proto_depIdxs = []int32{
	0, // 0: payment.PaymentService.ApplyCharge:input_type -> payment.ApplyChargeReq
	2, // 1: payment.PaymentService.CancelCharge:input_type -> payment.CancelChargeReq
	4, // 2: payment.PaymentService.QueryStatus:input_type -> payment.QueryStatusReq
	1, // 3: payment.PaymentService.ApplyCharge:output_type -> payment.ApplyChargeResp
	3, // 4: payment.PaymentService.CancelCharge:output_type -> payment.CancelChargeResp
	5, // 5: payment.PaymentService.QueryStatus:output_type -> payment.QueryStatusResp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
